# Generated by Django 3.1.4 on 2023-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20230501_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersurveyresponse',
            name='balance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellersurveyresponse',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
