# Generated by Django 3.1.4 on 2023-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20230501_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersurveyresponse',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
