# Generated by Django 3.1.4 on 2023-05-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20230501_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersurveyresponse',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
